apiVersion: v1
kind: Pod
metadata:
  name: 'car-serv'
  namespace: test-namespace
spec:
      containers:
      - name: car-serv
        image: elroydevops/car-serv
        ports: 
          - containerPort: 80